#%RAML 1.0 NamedExample
          [{
            movieID: 1,
            movieTitile: "Titanic",
            cinimaCode: "cin-01",
            startingTime: "10AM", 
            endingTime: "12AM", 
            movieType: "Romance", 
            price: 500.0
          }, 
          {
            movieID: 2,
            movieTitile: "Avangers",
            cinimaCode: "cin-02",
            startingTime: "9AM", 
            endingTime: "10AM", 
            movieType: "Advancher", 
            price: 700.0
          }, 
          {
            movieID: 3,
            movieTitile: "Avater",
            cinimaCode: "cin-01",
            startingTime: "10AM", 
            endingTime: "12AM", 
            movieType: "Sience Fiction",
            price: 800.0
          }]