#%RAML 1.0 NamedExample
          [{
            movieID: 00123,
            movieTitile: "Titanic",
            cinimaCode: "cin-01",
            startingTime: "10AM", 
            endingTime: "12AM", 
            type: "Romance"
          }, 
          {
            movieID: 00124,
            movieTitile: "Avangers",
            cinimaCode: "cin-02",
            startingTime: "9AM", 
            endingTime: "10AM", 
            type: "Advancher"
          }, 
          {
            movieID: 00125,
            movieTitile: "Avater",
            cinimaCode: "cin-01",
            startingTime: "10AM", 
            endingTime: "12AM", 
            type: "Sience Fiction"
          }]